<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Regresión logística – Página R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../analisis/reg-multiple.html" rel="prev">
<link href="../01_img/icono.png" rel="icon" type="image/png">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean",
  "openSidebar": false
}
</script>
<script async="" src="https://hypothes.is/embed.js"></script>
<script>
  window.document.addEventListener("DOMContentLoaded", function (_event) {
    document.body.classList.add('hypothesis-enabled');
  });
</script>
<style>
/* Estilos para todo el documento */
body {
  text-align: justify;
}
/* Estilos específicos para la tabla de contenidos */
.toc-actions, .toc .nav, .toc .nav > li > a {
  text-align: left !important;
}
</style>
<script>
// Añadir funcionalidad de zoom para imágenes
document.addEventListener('DOMContentLoaded', function() {
  document.querySelectorAll('img.zoomable').forEach(function(img) {
    img.addEventListener('click', function() {
      this.classList.toggle('zoomed');
    });
  });
});
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Página R</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Introducción a R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../df-var/ficheros-datos.html"> 
<span class="menu-text">Bases de datos y variables</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="../analisis/descriptivo.html" aria-current="page"> 
<span class="menu-text">Análisis de datos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../graficos/g-intro.html"> 
<span class="menu-text">Gráficos</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../otros.html"> 
<span class="menu-text">Otros</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://github.com/jorgeemm/Pagina_R" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-github"></i></a>
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title">Regresión logística</h1>
        </a>     
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/descriptivo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis descriptivo</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Análisis bivariado</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/teoria.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Teoría</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/ttest.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T-test</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/correlacion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Análisis de correlación</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/tablas-contingencia.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tablas de contingencia</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Regresiones</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/reg-lineal.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lineal simple</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/reg-multiple.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lineal múltiple</span></a>
  </div>
</li>
          <li class="sidebar-item">
 <span class="menu-text">analisis/predicciones.qmd</span>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../analisis/reg-logistica.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Regresión logística</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Contenido</h2>
   
  <ul>
  <li><a href="#análisis-de-clasificación" id="toc-análisis-de-clasificación" class="nav-link active" data-scroll-target="#análisis-de-clasificación">Análisis de clasificación</a></li>
  <li><a href="#regresión-logística-vs-regresión-lineal" id="toc-regresión-logística-vs-regresión-lineal" class="nav-link" data-scroll-target="#regresión-logística-vs-regresión-lineal">Regresión logística vs regresión lineal</a></li>
  <li><a href="#supuestos-básicos" id="toc-supuestos-básicos" class="nav-link" data-scroll-target="#supuestos-básicos">Supuestos básicos</a></li>
  <li><a href="#la-ecuación-de-la-regresión-logística" id="toc-la-ecuación-de-la-regresión-logística" class="nav-link" data-scroll-target="#la-ecuación-de-la-regresión-logística">La ecuación de la regresión logística</a></li>
  <li><a href="#ejercicio-de-regresión-logística" id="toc-ejercicio-de-regresión-logística" class="nav-link" data-scroll-target="#ejercicio-de-regresión-logística">Ejercicio de regresión logística</a></li>
  <li><a href="#estimación-del-modelo" id="toc-estimación-del-modelo" class="nav-link" data-scroll-target="#estimación-del-modelo">Estimación del modelo</a></li>
  <li><a href="#significatividad-de-las-variables" id="toc-significatividad-de-las-variables" class="nav-link" data-scroll-target="#significatividad-de-las-variables">Significatividad de las variables</a></li>
  <li><a href="#interpretación-de-los-coeficientes" id="toc-interpretación-de-los-coeficientes" class="nav-link" data-scroll-target="#interpretación-de-los-coeficientes">Interpretación de los coeficientes</a></li>
  <li><a href="#odds-ratio" id="toc-odds-ratio" class="nav-link" data-scroll-target="#odds-ratio">Odds ratio</a></li>
  <li><a href="#probabilidades-predichas" id="toc-probabilidades-predichas" class="nav-link" data-scroll-target="#probabilidades-predichas">Probabilidades predichas</a></li>
  <li><a href="#efectos-marginales" id="toc-efectos-marginales" class="nav-link" data-scroll-target="#efectos-marginales">Efectos marginales</a></li>
  <li><a href="#diagnóstico" id="toc-diagnóstico" class="nav-link" data-scroll-target="#diagnóstico">Diagnóstico</a></li>
  <li><a href="#presentación-de-los-resultados" id="toc-presentación-de-los-resultados" class="nav-link" data-scroll-target="#presentación-de-los-resultados">Presentación de los resultados</a></li>
  <li><a href="#validación-del-modelos-de-clasificaicón" id="toc-validación-del-modelos-de-clasificaicón" class="nav-link" data-scroll-target="#validación-del-modelos-de-clasificaicón">Validación del modelos de clasificaicón</a></li>
  <li><a href="#comparación-de-modelos" id="toc-comparación-de-modelos" class="nav-link" data-scroll-target="#comparación-de-modelos">Comparación de modelos</a>
  <ul class="collapse">
  <li><a href="#modelo-de-clasificación-random-forest" id="toc-modelo-de-clasificación-random-forest" class="nav-link" data-scroll-target="#modelo-de-clasificación-random-forest">Modelo de clasificación Random Forest</a></li>
  <li><a href="#modelo-de-clasificación-naive-bayes" id="toc-modelo-de-clasificación-naive-bayes" class="nav-link" data-scroll-target="#modelo-de-clasificación-naive-bayes">Modelo de clasificación Naive Bayes</a></li>
  </ul></li>
  <li><a href="#mejora-de-modelos" id="toc-mejora-de-modelos" class="nav-link" data-scroll-target="#mejora-de-modelos">Mejora de modelos</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Regresión logística</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="análisis-de-clasificación" class="level2">
<h2 class="anchored" data-anchor-id="análisis-de-clasificación">Análisis de clasificación</h2>
<p>La clasificación supervisada es una tarea muy frecuente en todas las áreas de análisis de datos. Existe un gran número de algoritmos desarrollados tanto por la estadística (regresión logística, análisis discriminante) como por la inteligencia artificial (redes neuronales, árboles de decisión, redes bayesianas) diseñados para realizar las tareas propias de la clasificación.</p>
<p>Vamos a centrarnos en el análisis de regresión logística, una técnica para el análisis de variables dependientes categóricas con dos categorías (<strong>dicotómicas</strong>) o más (<strong>polinómicas</strong>). Sirve para modelar la probabilidad de ocurrencia de un evento como función de otros factores, y responder preguntas como:</p>
<ul>
<li><p>¿Qué factores explican la victoria/derrota de un candidato en unas elecciones?</p></li>
<li><p>¿Qué variables determinan que una persona vote?</p></li>
<li><p>¿Qué factores incrementan/disminuyen el riesgo de caer en la pobreza?</p></li>
<li><p>¿Cómo podemos explicar el abandono escolar?</p></li>
<li><p>etc</p></li>
</ul>
<p>El análisis de regresión logística pertenece al grupo de <em>Modelos Lineales Generalizados</em> (GLM por sus siglas en inglés), y usa como función de enlace la función <em>logit</em>.</p>
</section>
<section id="regresión-logística-vs-regresión-lineal" class="level2">
<h2 class="anchored" data-anchor-id="regresión-logística-vs-regresión-lineal">Regresión logística vs regresión lineal</h2>
<p>El modelo de regresión lineal no es válido cuando la variable respuesta no tiene una distribución normal. Por ejemplo: respuestas si/no, conteos, probabilidades, etc.</p>
<p>Al igual que la regresión lineal, la regresión logística busca:</p>
<ul>
<li><p>predecir/explicar una VD a partir de una o mas VI,</p></li>
<li><p>medir el grado de relación de la VD con las VI</p></li>
<li><p>comprobar su significatividad</p></li>
</ul>
<p>A diferencia de la regresión lineal:</p>
<ul>
<li>los coeficientes de regresión se estiman por el procedimiento de <strong>Máxima Verosimilitud</strong>, que busca maximizar la probabilidad de ocurrencia del evento que se analiza</li>
</ul>
</section>
<section id="supuestos-básicos" class="level2">
<h2 class="anchored" data-anchor-id="supuestos-básicos">Supuestos básicos</h2>
<p><strong>Compartidos</strong> con la Regresión Lineal:</p>
<ul>
<li><p>Tamaño muestral elevado</p></li>
<li><p>Introducción de VIs relevantes</p></li>
<li><p>Variables predictoras continuas o dicotómicas</p></li>
<li><p>Ausencia de colinealidad entre las VIs</p></li>
<li><p>Aditividad</p></li>
</ul>
<p><strong>Específicos</strong>:</p>
<ul>
<li>No-linealidad: La función de vinculación logit es no-lineal. Esto implica que <strong>el cambio en la VD producido por el incremento de una unidad en la VI depende del valor que tome la variable</strong>. Es menos importante en los extremos de las VI, y mas importante en los valores centrales.</li>
</ul>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-2977121164.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="300"></p>
</figure>
</div>
<ul>
<li>Heterocedasticidad: En regresión logística se asume heterocedasticidad (varianza de los residuos no constante). Es lo contrario que en la regresión lineal, ya que la representación de la regresión logística no es lineal, sino que se busca que debe existir varianza en los residuos no constante.</li>
</ul>
</section>
<section id="la-ecuación-de-la-regresión-logística" class="level2">
<h2 class="anchored" data-anchor-id="la-ecuación-de-la-regresión-logística">La ecuación de la regresión logística</h2>
<p>La función de enlace logit, utilizada principalmente en modelos de regresión logística, es como hemos mencionado no lineal, ya que transforma una combinación lineal de predictores en probabilidades mediante la fórmula:</p>
<p><span class="math display">\[
\ln\left(\frac{p(x)}{1 - p(x)}\right) = \beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_p x_p
\]</span></p>
<p>En esta ecuación, la VD aparece en una forma que no es directamente interpretable (concretamente, el logaritmo neperiano de la razón de probabilidades). Haciendo transformaciones, podemos expresar la probabilidad de ocurrencia del suceso de la siguiente manera:</p>
<p><span class="math display">\[
p(x) = \frac{1}{1 + e^{-(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_p x_p)}} = \sigma\left(\beta_0 + \beta_1 x_1 + \beta_2 x_2 + \cdots + \beta_p x_p\right)
\]</span></p>
<p>donde:</p>
<p><span class="math display">\[
\sigma(x) = \frac{e^x}{1 + e^x} = \frac{1}{1 + e^{-x}}
\]</span></p>
</section>
<section id="ejercicio-de-regresión-logística" class="level2">
<h2 class="anchored" data-anchor-id="ejercicio-de-regresión-logística">Ejercicio de regresión logística</h2>
<p>Vamos a hacer un sencillo ejercicio de regresión logística usando los datos del la encuesta preelectoral CIS 2023. En concreto, vamos a estimar la probabilidad de que un individuo <em>i</em> tenga intención de votar a un parido <em>p</em> en las elecciones generales de 2023. Dado que se trata de un ejercicio de clase, vamos a incluir unas pocas variables y no vamos a tomar en consideración los casos perdidos (indecisos, etc). En consecuencia, los resultados no sirven para predicción electoral, solo practicar.</p>
<p>Como de costumbre, abrimos fichero “Limpieza de datos” en su versión más reciente.</p>
<p>A partir de la variable intención de voto (´INTENCIONG`), vamos a crear nuestra variable dependiente de intención voto VOX (<strong>intovox</strong>).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intención de voto</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(datos<span class="sc">$</span>INTENCIONG)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12   13   15   16   17 
7200 7592 2652   36   21   86   89  250  170    3    3    7   12    8    1    9 
  19   21   23   25  101  102  106  107  201  202  203  301  401  402  501  502 
   3 2877    1    6   10   18    2    2    4   57    3    6    1    2   66   16 
 601  801  802  803  804  808  809  814  901  902  903  904  905 1001 1101 1201 
   7   37   37   10    1    4    1    1  296  230   17  108   15   75    1  281 
1202 1301 1501 1502 1601 1602 1701 8993 8994 8995 8996 9977 9997 9998 9999 
   2    3   30    8  233  302    1   27    7  106  376  226  700 4084  762 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intención voto VOX</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">intvox =</span> <span class="fu">case_when</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>      INTENCIONG <span class="sc">==</span> <span class="dv">3</span> <span class="sc">~</span> <span class="dv">1</span>,            </span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>      INTENCIONG <span class="sc">&gt;=</span> <span class="dv">9977</span> <span class="sc">~</span> <span class="cn">NA</span>,  </span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(datos<span class="sc">$</span>intvox, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    0     1  &lt;NA&gt; 
20777  2652  5772 </code></pre>
</div>
</div>
<p>Como variables independientes, vamos a utilizar las variables “edad”, “hombre”, “estudios_universitarios”, “ecoesp”, “ideol” y “recuerdo19” que ya tenemos preparadas de clases anteriores. Una vez tenemos todas las variables preparadas, procedemos a crear el data.frame <strong>data</strong> con el conjunto de variables que vamos a incluir nuestros análisis y eliminamos los casos perdidos.</p>
<p><em>Que existan tantos casos perdidos en la variable dependiente (5772) no importa en este caso al ser un ejemplo, pero a la hora de hacer un modelo de predicción real se deberían imputar todos estos valores para que el modelo sea más fiable</em>.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>datos_log <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(intvox, hombre, estudios_universitarios, edad, ecoesp, ideol, recuerdo19) <span class="sc">%&gt;%</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>()</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     intvox          hombre      estudios_universitarios      edad      
 Min.   :0.0000   Mujer : 9373   sin EU:10482            Min.   :21.00  
 1st Qu.:0.0000   Hombre:10475   con EU: 9366            1st Qu.:41.00  
 Median :0.0000                                          Median :53.00  
 Mean   :0.1068                                          Mean   :52.78  
 3rd Qu.:0.0000                                          3rd Qu.:65.00  
 Max.   :1.0000                                          Max.   :95.00  
                                                                        
      ecoesp          ideol             recuerdo19  
 negativa:12417   Min.   : 1.000   PSOE      :7104  
 positiva: 7431   1st Qu.: 3.000   PP        :4557  
                  Median : 5.000   Otros     :2534  
                  Mean   : 4.817   Podemos   :2292  
                  3rd Qu.: 7.000   VOX       :1648  
                  Max.   :10.000   Ciudadanos:1360  
                                   (Other)   : 353  </code></pre>
</div>
</div>
</section>
<section id="estimación-del-modelo" class="level2">
<h2 class="anchored" data-anchor-id="estimación-del-modelo">Estimación del modelo</h2>
<p>Ya podemos estimar la regresión logística. De las 4 variables dependientes que tenemos, vamos a empezamos por calcular la probabilidad de votar a VOX frente a otros partidos, en función de la ideología, recuerdo de voto en 2019, opinión sobre la economía en España y perfil socio-demográfico de la persona. Usamos la función <code>glm()</code> con <em>link function</em> binominal.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>m.vox <span class="ot">&lt;-</span> <span class="fu">glm</span>(intvox <span class="sc">~</span> hombre <span class="sc">+</span> estudios_universitarios <span class="sc">+</span> edad <span class="sc">+</span> ecoesp <span class="sc">+</span> ideol <span class="sc">+</span> recuerdo19, <span class="at">data =</span> datos_log, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m.vox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = intvox ~ hombre + estudios_universitarios + edad + 
    ecoesp + ideol + recuerdo19, family = "binomial", data = datos_log)

Coefficients:
                               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                   -3.488087   0.164352 -21.223  &lt; 2e-16 ***
hombreHombre                   0.758371   0.064308  11.793  &lt; 2e-16 ***
estudios_universitarioscon EU -0.266082   0.063597  -4.184 2.87e-05 ***
edad                          -0.027296   0.002093 -13.043  &lt; 2e-16 ***
ecoesppositiva                -1.352050   0.109386 -12.360  &lt; 2e-16 ***
ideol                          0.290559   0.016197  17.939  &lt; 2e-16 ***
recuerdo19PP                   0.478263   0.107785   4.437 9.11e-06 ***
recuerdo19VOX                  3.378650   0.109928  30.735  &lt; 2e-16 ***
recuerdo19Podemos             -0.313977   0.206227  -1.522    0.128    
recuerdo19Ciudadanos           0.693385   0.127396   5.443 5.25e-08 ***
recuerdo19Más Madrid          -1.109060   1.011114  -1.097    0.273    
recuerdo19Otros               -0.266386   0.164990  -1.615    0.106    
recuerdo19En blanco           -0.123526   0.340733  -0.363    0.717    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 13484.3  on 19847  degrees of freedom
Residual deviance:  7595.5  on 19835  degrees of freedom
AIC: 7621.5

Number of Fisher Scoring iterations: 7</code></pre>
</div>
</div>
</section>
<section id="significatividad-de-las-variables" class="level2">
<h2 class="anchored" data-anchor-id="significatividad-de-las-variables">Significatividad de las variables</h2>
<p>Al igual que en la regresión lineal, contrastamos las siguientes hipótesis:</p>
<ul>
<li><p>H<sub>0</sub>:βi=0 -&gt; la VI<sub>i</sub> no tiene efecto sobre la VD</p></li>
<li><p>H<sub>a</sub>:βi!=0 -&gt;la VI<sub>i</sub> sí tiene efecto sobre la VD</p></li>
</ul>
<p>Como ya sabemos, podemos rechazar la hipótesis nula siempre que:</p>
<ul>
<li><p>p-valor&lt;0.05, NC:95%</p></li>
<li><p>p-valor&lt;0.01, NC:99%</p></li>
<li><p>p-valor&lt;0.001, NC:99.9%</p></li>
</ul>
<p>Si además queremos calcular los intervalos de confianza, podemos usar la función <code>cofint()</code></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">confint</span>(m.vox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                    2.5 %      97.5 %
(Intercept)                   -3.81281533 -3.16847185
hombreHombre                   0.63278731  0.88491727
estudios_universitarioscon EU -0.39093054 -0.14158952
edad                          -0.03141038 -0.02320544
ecoesppositiva                -1.57030106 -1.14124336
ideol                          0.25887651  0.32237807
recuerdo19PP                   0.26914384  0.69187062
recuerdo19VOX                  3.16575149  3.59683507
recuerdo19Podemos             -0.73570089  0.07550088
recuerdo19Ciudadanos           0.44317980  0.94295525
recuerdo19Más Madrid          -3.98404616  0.41077929
recuerdo19Otros               -0.59785450  0.05018137
recuerdo19En blanco           -0.85381772  0.49558218</code></pre>
</div>
</div>
</section>
<section id="interpretación-de-los-coeficientes" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-de-los-coeficientes">Interpretación de los coeficientes</h2>
<p>Los estimadores representan el logaritmo del cociente de probabilidades. Por ejemplo, ceteris paribus:</p>
<ul>
<li><p>Ideología: Para cada punto que aumenta la ideología, el log de la probabilidad de votar a VOX (versus votar otro partido) aumenta en 0.290559.</p></li>
<li><p>Votó PP en 2019: el logaritmo de la probabilidad de votar a VOX en 2023 es 0.478263 mayor que entre los que en 2019 votaron al PP que entre los que votaron al PSOE (categoría de referencia).</p></li>
</ul>
<p>Como se puede observar, esta interpretación de los coeficientes es muy poco intuitiva. Este tipo de coeficiente es útil si lo que nos interesa es conocer la dirección del efecto (signo positivo o negativo) y el nivel de significación (p-valor). Si por el contrario estamos interesados en interpretar el valor coeficiente, tenemos dos alternativas mejores: expresar los coeficientes como <em>odds ratio</em> o calcular las probabilidades de ocurrencia del evento.</p>
</section>
<section id="odds-ratio" class="level2">
<h2 class="anchored" data-anchor-id="odds-ratio">Odds ratio</h2>
<p>Con el <em>odds</em> <em>ratio</em> lo que hago es exponenciar el coeficiente, osea e exponencial de Beta: <span class="math inline">\(e^{\text{coef}}\)</span> y es la frecuencia de ocurrencia de un suceso sobre la frecuencia de su no ocurrencia:</p>
<ul>
<li><p>Odds ratio &gt;1: la variable tiene un efecto positivo sobre la probabilidad de ocurrencia del suceso.</p></li>
<li><p>0 &gt; Odds ratio &lt;1: la variable tiene un efecto negativo sobre la probabilidad de ocurrencia del suceso.</p></li>
<li><p>Odds ratio =1: la variable no tiene efecto sobre la probabilidad de ocurrencia del suceso.</p></li>
</ul>
<p>En la tabla:</p>
<ul>
<li><p>Odds ratio<sub>ideología</sub>=e<sup>0.290559</sup>=1.337. Para cada punto que nos movemos a la derecha en la escala de ideología, la probabilidad de votar a VOX (sobre votar a otro partido) aumenta en un factor de 1.337 (cuando el resto de variables permanecen constantes). O si se quiere expresar en porcentaje.</p>
<ul>
<li>(1,337 - 1)* 100 = 0,337 * 100 = 33,7%</li>
</ul>
<p>Sale 1,33, el cual es el mismo valor del coeficiente solo que ahora lo calcula las betas elevadas a <span class="math inline">\(e\)</span> para desahacer el logaritmo neperiano.</p></li>
<li><p>Odds ratio<sub>votó&nbsp;PP(2019)</sub>= e<sup>0.478263</sup>=1,61. La probabilidad de votar a VOX (sobre votar a otro partido) es 1,61 veces mayor entre las personas que en 2019 votaron al PP que entre las personas que en 2019 votaron al PSOE (cuando el resto de variables permanecen constantes). O si se quiere expresar en porcentaje.</p>
<ul>
<li>(1,61 - 1)* 100 = 0,61 * 100 = 61%</li>
</ul></li>
<li><p>En el caso de que el coeficiente sea negativo, como por ejemplo “opinión sobre la situación de la economía en España” haríamos así: Odds ratio<sub>ecoesp</sub>=e<sup>-1.352050</sup>=0.259. En este caso, la probabilidad de votar a VOX es 0.259 veces menor entre las personas que consideran que la economía nacional va bien, que entre los que consideran que la economía nacional va mal (ceteris paribus). Expresado en porcentaje, sería:</p>
<ul>
<li>(1 - 0.259)* 100 = 0.741 * 100 = 74%</li>
</ul></li>
</ul>
<p>Para obtener los coeficientes exponenciados usamos la función <code>exp()</code>: Con este código le estoy pidiendo los odds ratio porque le estoy pidiendo el exponente de los coeficientes de la regresión logística.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">coef</span>(m.vox))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  (Intercept)                  hombreHombre 
                   0.03055927                    2.13479521 
estudios_universitarioscon EU                          edad 
                   0.76637648                    0.97307287 
               ecoesppositiva                         ideol 
                   0.25870935                    1.33717441 
                 recuerdo19PP                 recuerdo19VOX 
                   1.61327017                   29.33114991 
            recuerdo19Podemos          recuerdo19Ciudadanos 
                   0.73053605                    2.00047661 
         recuerdo19Más Madrid               recuerdo19Otros 
                   0.32986896                    0.76614347 
          recuerdo19En blanco 
                   0.88379885 </code></pre>
</div>
</div>
<p>Para ponerlo todo en una tabla, usamos la función <code>cbind</code> (<em>column bind</em>), que nos permite unir la columna de los coeficientes y la de los intervalos de confianza.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="fu">cbind</span>(<span class="at">OR =</span> <span class="fu">coef</span>(m.vox), <span class="fu">confint</span>(m.vox)))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                       OR       2.5 %      97.5 %
(Intercept)                    0.03055927  0.02208591  0.04206783
hombreHombre                   2.13479521  1.88285136  2.42278395
estudios_universitarioscon EU  0.76637648  0.67642714  0.86797747
edad                           0.97307287  0.96907780  0.97706174
ecoesppositiva                 0.25870935  0.20798256  0.31942162
ideol                          1.33717441  1.29547382  1.38040656
recuerdo19PP                   1.61327017  1.30884340  1.99744850
recuerdo19VOX                 29.33114991 23.70655269 36.48258675
recuerdo19Podemos              0.73053605  0.47916950  1.07842418
recuerdo19Ciudadanos           2.00047661  1.55765237  2.56755800
recuerdo19Más Madrid           0.32986896  0.01861019  1.50799250
recuerdo19Otros                0.76614347  0.54999038  1.05146178
recuerdo19En blanco            0.88379885  0.42578629  1.64145359</code></pre>
</div>
</div>
<p><strong>Comparar coeficientes</strong></p>
<p>Los odds ratio se pueden comparar entre sí para saber qué variable es más explicativa o está asociada de manera más fuerte con la VD. Pero OJO! Para comparar un odds ratio mayor que uno (relación positiva) con un odds ratio menor que uno (relación negativa), es necesario calcular el valor inverso de uno de los datos porque el rango es distinto. Por ejemplo:</p>
<ul>
<li>ecoesp: 1/0,259=3,86</li>
</ul>
<p>Cuando hacemos esto para poder comparar debemos tener en cuenta que este coeficiente es para la variable de referencia. En este caso 3,86 es para la economíanegativa, porque estamos dandole la vuelta al numerador y denominador.</p>
<p>La inversión de variables también es útil en el caso de las variables dicotómicas para comprobar el supuesto contrario al establecido. Por ejemplo, la probabilidad de las mujeres (en lugar del de los hombres) es de 1/2,13=0,47.</p>
<p>Se puede hacer para cualquier tipo de variable, en el caso de la categóricas se invierte a su variable de referencias, y en el caso de las de escala (como la variable ideologia) lo entendemos como el aumento de una unidad.</p>
</section>
<section id="probabilidades-predichas" class="level2">
<h2 class="anchored" data-anchor-id="probabilidades-predichas">Probabilidades predichas</h2>
<p>Como alternativa a los coeficientes y a los odds ratio se pueden calcular las probabilidades predichas. Las probabilidades predichas son la mejor manera de entender las variables de un modelo. Para calcularlas, primero debemos crear un <em>data.frame</em> con los valores que queremos que tomen las variables independientes en nuestras predicciones.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>data1 <span class="ot">&lt;-</span> <span class="fu">with</span>(datos_log, <span class="fu">data.frame</span>(<span class="at">ideol =</span> <span class="fu">mean</span>(ideol), <span class="at">recuerdo19 =</span> <span class="fu">c</span>(<span class="st">"PSOE"</span>,<span class="st">"PP"</span>,<span class="st">"VOX"</span>,<span class="st">"Podemos"</span>,<span class="st">"Ciudadanos"</span>, <span class="st">"Más Madrid"</span>, <span class="st">"Otros"</span>, <span class="st">"En blanco"</span>), <span class="at">edad =</span> <span class="fu">mean</span>(edad), <span class="at">hombre=</span><span class="st">"Hombre"</span>, <span class="at">estudios_universitarios=</span><span class="st">"con EU"</span>, <span class="at">ecoesp=</span><span class="st">"negativa"</span>))</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(data1, <span class="dv">8</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     ideol recuerdo19     edad hombre estudios_universitarios   ecoesp
1 4.816505       PSOE 52.77877 Hombre                  con EU negativa
2 4.816505         PP 52.77877 Hombre                  con EU negativa
3 4.816505        VOX 52.77877 Hombre                  con EU negativa
4 4.816505    Podemos 52.77877 Hombre                  con EU negativa
5 4.816505 Ciudadanos 52.77877 Hombre                  con EU negativa
6 4.816505 Más Madrid 52.77877 Hombre                  con EU negativa
7 4.816505      Otros 52.77877 Hombre                  con EU negativa
8 4.816505  En blanco 52.77877 Hombre                  con EU negativa</code></pre>
</div>
</div>
<p>Este código predice con la media de ideología en la muestra en vez de con ideología = 5, para todos los recuerdos de voto, que esté en la media de edad de la muestra, que sea hombre, con estudios y con una opinión negativa para la economía.</p>
<p>Es importante que las variables en este <em>data.frame</em> tengan el mismo nombre que las variables en la regresión logística anterior. Una vez creado el <em>data.frame</em>, ya podemos pedirle a R que calcule las probabilidades predichas.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>data1<span class="sc">$</span>probpredichas_vox<span class="ot">&lt;-</span> <span class="fu">predict</span>(m.vox, <span class="at">newdata =</span> data1, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>data1[, <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">7</span>)]  <span class="co">#le pido que muestre todas las filas de las columnas 2 (recuerdo voto) y 7(probabilidad predicha)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  recuerdo19 probpredichas_vox
1       PSOE        0.04578266
2         PP        0.07184266
3        VOX        0.58459468
4    Podemos        0.03386365
5 Ciudadanos        0.08757578
6 Más Madrid        0.01558029
7      Otros        0.03545569
8  En blanco        0.04067907</code></pre>
</div>
</div>
<p>Los resultados muestran la probabilidad predicha de votar a VOX en 2023 para hombres con edad media, ideología media y con estudios universitarios, que opinan que la economía en España va mal, según el partido que habían votado en las elecciones anteriores.</p>
</section>
<section id="efectos-marginales" class="level2">
<h2 class="anchored" data-anchor-id="efectos-marginales">Efectos marginales</h2>
<p>El paquete <em>margins</em> responde a un intento de trasladar el comando “margins” de Stata a R, como un método genérico para calcular los efectos marginales -o efectos parciales- de las variables independientes. Por ejemplo, vamos calcular el efecto marginal de las VIs en nuestro modelo</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(margins)</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>margins_vox <span class="ot">&lt;-</span> <span class="fu">margins</span>(m.vox)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Resumen</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>summary_margins <span class="ot">&lt;-</span> <span class="fu">summary</span>(margins_vox) </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>summary_margins</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                        factor     AME     SE        z      p   lower   upper
                ecoesppositiva -0.0621 0.0042 -14.6920 0.0000 -0.0704 -0.0538
                          edad -0.0015 0.0001 -13.0236 0.0000 -0.0017 -0.0012
 estudios_universitarioscon EU -0.0142 0.0034  -4.1951 0.0000 -0.0208 -0.0076
                  hombreHombre  0.0405 0.0034  11.9060 0.0000  0.0339  0.0472
                         ideol  0.0155 0.0009  17.8011 0.0000  0.0138  0.0172
          recuerdo19Ciudadanos  0.0365 0.0071   5.1327 0.0000  0.0225  0.0504
           recuerdo19En blanco -0.0047 0.0124  -0.3784 0.7051 -0.0291  0.0197
          recuerdo19Más Madrid -0.0289 0.0159  -1.8197 0.0688 -0.0601  0.0022
               recuerdo19Otros -0.0096 0.0057  -1.6861 0.0918 -0.0208  0.0016
             recuerdo19Podemos -0.0111 0.0067  -1.6524 0.0985 -0.0243  0.0021
                  recuerdo19PP  0.0231 0.0049   4.6900 0.0000  0.0135  0.0328
                 recuerdo19VOX  0.3882 0.0146  26.5553 0.0000  0.3596  0.4169</code></pre>
</div>
</div>
<p>También podemos representarlos gráficamente. El gráfico a continuación representa la columna AME (<em>Average Marginal Effect</em>) y las columnas <em>low</em> and <em>upper</em> (bandas de confianza inferior y superior).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertimos el resumen en un data.frame para poder hacer un gráfico</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>data_to_plot <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">factor =</span> summary_margins<span class="sc">$</span>factor,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">AME =</span> summary_margins<span class="sc">$</span>AME,</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">lower =</span> summary_margins<span class="sc">$</span>lower,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">upper =</span> summary_margins<span class="sc">$</span>upper)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_to_plot, <span class="fu">aes</span>(<span class="at">x =</span> AME, <span class="at">y =</span> factor)) <span class="sc">+</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">"blue"</span>, <span class="at">size =</span> <span class="dv">3</span>) <span class="sc">+</span>  <span class="co"># Puntos para los AME</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_errorbarh</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> lower, <span class="at">xmax =</span> upper), <span class="at">height =</span> <span class="fl">0.2</span>, <span class="at">color =</span> <span class="st">"black"</span>) <span class="sc">+</span>  <span class="co"># Barras de error</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">0</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"grey"</span>) <span class="sc">+</span>  <span class="co"># Línea vertical en 0</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Average Marginal Effects (AME) with Confidence Intervals"</span>,</span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"AME"</span>,</span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Variables"</span>) <span class="sc">+</span></span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">size =</span> <span class="dv">14</span>),  <span class="co"># Centrar título</span></span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>))  <span class="co"># Ajustar tamaño de texto</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reg-logistica_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>Interpretación: Cuando se dice que un efecto marginal es 0.3882, significa que haber votado a VOX en 2019 está asociado con un aumento promedio de 0.17 unidades en la variable dependiente. En el contexto de una probabilidad o un porcentaje, como suele ser el caso en la regresión logística o modelos similares, un efecto marginal de 0.3882 corresponde a un aumento del 38,82 puntos porcentuales.</p>
<p>Para hacer un modelo robusto puedes elegir poner las variables con sus valores que conformarían el escenario mas adverso. El escenario que más desfavorece la hipótesis planteada.</p>
<p>Para más información sobre opciones del paquete margins podéis consultar <a href="https://www.rdocumentation.org/packages/margins/versions/0.3.23">aquí</a> y <a href="https://cran.r-project.org/web/packages/margins/vignettes/Introduction.html">aquí</a>.</p>
<p><strong>Resumen</strong></p>
<p>La primera transformación es pasar el logaritmo al otro lado, es decir <span class="math inline">\(e^{\text{coef}}\)</span> –&gt; los odds ratios, porque al otro lado del igual queda <span class="math inline">\((\frac{p(x)}{1 - p(x)})\)</span> , es decir la probabilidad del que el evento suceda partido de la probabilidad de que no suceda.</p>
<p>La última transfomación de la ecuación nos deja despejado <span class="math inline">\(p(x)\)</span>, de esta manera podemos hacer probabilidades predichas de x sustituyendo los betas y las x (como hacías valores predichos en lm). Como la distribución de la muestra no es lineal los efectos de x no son iguales a lo largo de todo y, de esta manera podemos calcular casos específicos de y. Podemos conocer a lo largo de la regresión la probabilidad de y para cada x seleccionada por nosotros.</p>
<p>Por último podemos calcular los <em>Average</em> <em>Marginal</em> <em>Effects</em> (<em>margins</em> en Stata). El efecto marginal no es la probabilidad de ocurrencia de x, sino el fecto de la VI sobre la probabilidad de ocurrencia de x. Es la manera de conseguir el equivalente a los coeficientes de la regresión lineal porque calcular todas las y para ciertos valores de x y luego hace el promedio de esos impactos de la x. En el caso de lineales no hace falta transformar nada porque la media del efectos de una VI sobre todos los valores de y es igual a el efecto de de VI sobre un solo valor de y porque es un efecto estable a lo largo de toda la regresión.</p>
<p>AME se usa principalmente cuando tienes un interés particular por el efecto de una VI.</p>
</section>
<section id="diagnóstico" class="level2">
<h2 class="anchored" data-anchor-id="diagnóstico">Diagnóstico</h2>
<section id="multicolinealidad" class="level4">
<h4 class="anchored" data-anchor-id="multicolinealidad">Multicolinealidad</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rms)</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>logit.vif<span class="ot">&lt;-</span> <span class="fu">vif</span>(m.vox)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>logit.vif</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 hombreHombre estudios_universitarioscon EU 
                     1.032483                      1.048952 
                         edad                ecoesppositiva 
                     1.077446                      1.058599 
                        ideol                  recuerdo19PP 
                     1.428741                      2.968629 
                recuerdo19VOX             recuerdo19Podemos 
                     2.498353                      1.189084 
         recuerdo19Ciudadanos          recuerdo19Más Madrid 
                     1.726136                      1.006883 
              recuerdo19Otros           recuerdo19En blanco 
                     1.295863                      1.061883 </code></pre>
</div>
</div>
<p>Todos los valores están por debajo de 5. No parece que existan problemas de multicolinealidad</p>
</section>
<section id="heterocedasticidad" class="level4">
<h4 class="anchored" data-anchor-id="heterocedasticidad">Heterocedasticidad</h4>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmtest)</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>logit.het<span class="ot">&lt;-</span><span class="fu">bptest</span>(m.vox)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>logit.het</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    studentized Breusch-Pagan test

data:  m.vox
BP = 2273.9, df = 12, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>La hipótesis nula en este test es que la varianza de los residuos es constante. La evidencia permite rechazar la hipótesis nula, confirmando que se cumple el supuesto de heterocedasticidad (que es lo que buscamos).</p>
</section>
</section>
<section id="presentación-de-los-resultados" class="level2">
<h2 class="anchored" data-anchor-id="presentación-de-los-resultados">Presentación de los resultados</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(stargazer)</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">stargazer</span>(m.vox,</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>          <span class="at">type=</span><span class="st">"text"</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>          <span class="at">dep.var.labels=</span><span class="fu">c</span>(<span class="st">"Voto VOX"</span>),</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>          <span class="at">covariate.labels=</span><span class="fu">c</span>(<span class="st">"Hombre"</span>, <span class="st">"Estudios Universitarios"</span>, <span class="st">"Edad"</span>, <span class="st">"Valoración + economia"</span>, <span class="st">"Ideología"</span>, <span class="st">"Voto 2019: PP (cr:PSOE)"</span>, <span class="st">"Voto 2019: VOX (cr:PSOE)"</span>, <span class="st">"Voto 2019: Podemos (cr:PSOE)"</span>, <span class="st">"Voto 2019: Ciudadanos (cr:PSOE)"</span>, <span class="st">"Voto 2019: +Madrid (cr:PSOE)"</span>, <span class="st">"Voto 2019: Otros (cr:PSOE)"</span>, <span class="st">"Voto 2019: blanco (cr:PSOE)"</span>, <span class="st">"Constante"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
===========================================================
                                    Dependent variable:    
                                ---------------------------
                                         Voto VOX          
-----------------------------------------------------------
Hombre                                   0.758***          
                                          (0.064)          
                                                           
Estudios Universitarios                  -0.266***         
                                          (0.064)          
                                                           
Edad                                     -0.027***         
                                          (0.002)          
                                                           
Valoración + economia                    -1.352***         
                                          (0.109)          
                                                           
Ideología                                0.291***          
                                          (0.016)          
                                                           
Voto 2019: PP (cr:PSOE)                  0.478***          
                                          (0.108)          
                                                           
Voto 2019: VOX (cr:PSOE)                 3.379***          
                                          (0.110)          
                                                           
Voto 2019: Podemos (cr:PSOE)              -0.314           
                                          (0.206)          
                                                           
Voto 2019: Ciudadanos (cr:PSOE)          0.693***          
                                          (0.127)          
                                                           
Voto 2019: +Madrid (cr:PSOE)              -1.109           
                                          (1.011)          
                                                           
Voto 2019: Otros (cr:PSOE)                -0.266           
                                          (0.165)          
                                                           
Voto 2019: blanco (cr:PSOE)               -0.124           
                                          (0.341)          
                                                           
Constante                                -3.488***         
                                          (0.164)          
                                                           
-----------------------------------------------------------
Observations                              19,848           
Log Likelihood                          -3,797.747         
Akaike Inf. Crit.                        7,621.493         
===========================================================
Note:                           *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01</code></pre>
</div>
</div>
</section>
<section id="validación-del-modelos-de-clasificaicón" class="level2">
<h2 class="anchored" data-anchor-id="validación-del-modelos-de-clasificaicón">Validación del modelos de clasificaicón</h2>
<p>A continuación, vamos examinar cómo de bueno/malo es nuestro modelo a la hora de clasificar datos nuevos. Para ello, continuamos con el ejemplo anterior, en el que estimábamos la probabilidad de que un individiuo vote a un determinado partido. Se llama clasficación porque estoy intentado clasificar a los individuos en función de los valores de la VD, que en este caso es 0 y 1.</p>
<p>En primer lugar, creamos el conjunto de entrenamiento (60%) y test (40%). Como hay pocos 1 en la muestra (de la var dependiente), se amplia el % de casos destinados al test para evitar que dentro de este la proporción de 1 sea demasiado bajo como para comprobar el modelo.Se saca una muestra aleatoria y por eso ponermos el seed, para que nos escoja los mismos datos aleatorios y sea replicable.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>index <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(datos_log)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>porc_test <span class="ot">&lt;-</span> <span class="fl">0.40</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir datos</span></span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>test.data <span class="ot">&lt;-</span> datos_log <span class="sc">%&gt;%</span> <span class="fu">sample_frac</span>(porc_test)  </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>train.data <span class="ot">&lt;-</span> datos_log <span class="sc">%&gt;%</span> <span class="fu">anti_join</span>(test.data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Creamos la variable&nbsp;<strong>clase_real</strong>, que corresponde a la variable dependiente (intentación voto a VOX) en el conjunto de test. Es la variable que luego comparemos con los valores estimados para ver nuestro nivel de acierto/error:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>clase_real <span class="ot">&lt;-</span> test.data<span class="sc">$</span>intvox</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Entrenamos el modelo (intención de voto a VOX) con los datos del train.data:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(MASS)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>logit.vox <span class="ot">&lt;-</span> <span class="fu">glm</span>(intvox <span class="sc">~</span> hombre <span class="sc">+</span> estudios_universitarios <span class="sc">+</span> edad <span class="sc">+</span> ecoesp <span class="sc">+</span> ideol <span class="sc">+</span> recuerdo19, <span class="at">data =</span> train.data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit.vox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = intvox ~ hombre + estudios_universitarios + edad + 
    ecoesp + ideol + recuerdo19, family = "binomial", data = train.data)

Coefficients:
                               Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                   -2.647381   0.223754 -11.832  &lt; 2e-16 ***
hombreHombre                   0.514395   0.091050   5.650 1.61e-08 ***
estudios_universitarioscon EU -0.201434   0.089109  -2.261 0.023788 *  
edad                          -0.019516   0.002758  -7.077 1.47e-12 ***
ecoesppositiva                -1.382171   0.133390 -10.362  &lt; 2e-16 ***
ideol                          0.203899   0.021920   9.302  &lt; 2e-16 ***
recuerdo19PP                   0.952857   0.142989   6.664 2.67e-11 ***
recuerdo19VOX                  2.713181   0.147704  18.369  &lt; 2e-16 ***
recuerdo19Podemos             -0.421267   0.245799  -1.714 0.086553 .  
recuerdo19Ciudadanos           0.585503   0.168807   3.468 0.000523 ***
recuerdo19Más Madrid          -1.237565   1.017536  -1.216 0.223895    
recuerdo19Otros               -0.600585   0.217137  -2.766 0.005676 ** 
recuerdo19En blanco           -0.948500   0.526124  -1.803 0.071418 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5182.6  on 5941  degrees of freedom
Residual deviance: 3442.7  on 5929  degrees of freedom
AIC: 3468.7

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>Después, calculamos los valores predichos en el conjunto de test. Estos son los valores que luego vamos a comparar con la “clase real”:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>predicted_logit<span class="ot">&lt;-</span> <span class="fu">predict</span>(logit.vox, <span class="at">newdata=</span>test.data, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(predicted_logit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          1           2           3           4           5           6 
0.006046023 0.024786792 0.050014734 0.009515188 0.213903071 0.064099475 </code></pre>
</div>
</div>
<p>Para valorar cómo de bien/mal clasifica nuestro modelo, vamos a calcular la curva ROC(<em>Receiver operating characteristics</em>) y el AUC (<em>Area under the curve</em>). Cuando hacemos una clasificación binaria, existen 4 tipos de resultados posibles:</p>
<ul>
<li><p>True negative (TN): predecimos 0 y la clase real es 0</p></li>
<li><p>False negative (FN): predecimos 0 y la clase real es 1</p></li>
<li><p>True positive (TP): predecimos 1 y la clase real es 1</p></li>
<li><p>False positive (FP): predecimos 1 y la clase real es 0</p></li>
</ul>
<p>A partir de estos resultados se construye la <em>matriz de confusión</em>:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-2798392842.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="400"></p>
</figure>
</div>
<p>La matriz de confusión sive para calcular la <strong>curva ROC</strong>, que es la representación gráfico de la razón de Verdaderos Positivos (TPR) frente a la razón de falsos positivos (FPR):</p>
<ul>
<li>Razón de verdaderos positivos (TPR - true positive rate): proporción de positivos reales que son correctamente identificados como positivos por el modelo. También se le conoce como sensibilidad o recall. Se calcula como:</li>
</ul>
<p><span class="math display">\[
TPR = \frac{TP}{TP + FN}
\]</span></p>
<ul>
<li>Razón de falsos positivos (FPR - false positive rate) = proporción de negativos reales que son incorrectamente identificados como positivos por el modelo. Se calcula como:</li>
</ul>
<p><span class="math display">\[
FPR = \frac{FP}{FP + TN}
\]</span></p>
<p>Gráficamente, el espacio ROC se representa de la siguiente manera:</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/clipboard-2824448575.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="400"></p>
</figure>
</div>
<p>Lo ideal es encontrar una curva que se acerque lo máximo posible al punto de clasificación perfecta. Si está en la línea, los resultados de la predicción son completamente aleatorios, y si está por debajo de esta el modelo predice aún peor que asignar cifras al azar.</p>
<p>Pintamos la curva ROC de nuestro modelo:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ROCR)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Curva ROC</span></span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>pred_logit <span class="ot">&lt;-</span>  <span class="fu">prediction</span>(predicted_logit, clase_real) <span class="co"># crea un objeto "predicción"</span></span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>perf_logit <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_logit, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>) </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_logit, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">"darkgrey"</span>, <span class="at">main =</span> <span class="st">"Logit ROC Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reg-logistica_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>Esto se interpreta en función del area que hay debajo de la línea, lo ideal es que el area sea 1 (100%) es decir, que todo lo ha clasificado bien.</p>
<p>Calculamos el area bajo la curva (AUC). El AUC (Área Bajo la Curva) es una métrica que mide el desempeño de un modelo de clasificación binaria. Un valor de AUC:</p>
<ul>
<li><p>1.0: El modelo clasifica perfectamente todas las instancias</p></li>
<li><p>0.5: El modelo no tiene poder predictivo (es como adivinar al azar)</p></li>
<li><p>&lt; 0.5: El modelo clasifica peor que al azar.</p></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>auc.logit<span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_logit, <span class="at">measure =</span> <span class="st">"auc"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>) </span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>auc.logit<span class="sc">@</span>y.values </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.9201428</code></pre>
</div>
</div>
<p>En nuestro caso, AUC=0.920. Este valor indica que nuestro modelo clasifica bien en un 92% por de los casos.</p>
<p>Nota: AUC es un <em>S4 object system</em>, por eso las consultas de sus elementos son un poco diferentes a lo que hemos visto hasta ahora. Nosotros no vamos a entrar en esto, pero si teneís curiosidad podéis leer <a href="http://adv-r.had.co.nz/S4.html">este capítulo del libro de Hadley Wickham</a>.</p>
</section>
<section id="comparación-de-modelos" class="level2">
<h2 class="anchored" data-anchor-id="comparación-de-modelos">Comparación de modelos</h2>
<p>Normalmente, la curva ROC se utiliza para comparar la precisión de diferentes algoritmos de clasificación (como regresión logística, Naive Bayes, Random Forest, LDA, etc). Aunque en nuestro caso solo hemos trabajado con regresión logística, vamos a estimar diferentes modelos a modo de ejemplo, pero sin profundizar en los detalles de su funcionamiento.</p>
<section id="modelo-de-clasificación-random-forest" class="level3">
<h3 class="anchored" data-anchor-id="modelo-de-clasificación-random-forest">Modelo de clasificación Random Forest</h3>
<p>Empezamos con un <a href="https://www.r-bloggers.com/2021/04/random-forest-in-r/">random forest</a></p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(randomForest)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Convertimos la variable intvoto en factor (de lo contrario, da error)</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>train.data<span class="sc">$</span>intvox <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(train.data<span class="sc">$</span>intvox)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>test.data<span class="sc">$</span>intvox <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(test.data<span class="sc">$</span>intvox)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Entrenamos el modelo Random Forest </span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>rf.vox <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  intvox <span class="sc">~</span> hombre <span class="sc">+</span> estudios_universitarios <span class="sc">+</span> edad <span class="sc">+</span> ecoesp <span class="sc">+</span> ideol <span class="sc">+</span> recuerdo19,</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train.data,</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">ntree =</span> <span class="dv">500</span>,      <span class="co"># número de árboles</span></span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">mtry =</span> <span class="dv">2</span>,         <span class="co"># número de predictores seleccionados aleatoriamente por árbol</span></span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">importance =</span> <span class="cn">TRUE</span> <span class="co"># importancia de variables</span></span>
<span id="cb38-14"><a href="#cb38-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb38-15"><a href="#cb38-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-16"><a href="#cb38-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Importancia de las variables</span></span>
<span id="cb38-17"><a href="#cb38-17" aria-hidden="true" tabindex="-1"></a><span class="fu">importance</span>(rf.vox) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                 0          1 MeanDecreaseAccuracy
hombre                  12.8426166   9.205945             16.10155
estudios_universitarios 17.3804480   1.960043             15.25825
edad                    31.4921348  10.755326             31.06569
ecoesp                   0.3002038  24.733429             24.64840
ideol                   29.2955504  20.302083             45.27504
recuerdo19              63.0086066 104.221899             96.01329
                        MeanDecreaseGini
hombre                          20.12300
estudios_universitarios         19.83165
edad                           157.91882
ecoesp                          59.64442
ideol                          149.24749
recuerdo19                     374.84054</code></pre>
</div>
</div>
<p>Le indicamos que haga 500 arboles; mtry es el número de predictores seecionados aleatoriamente. Importance indica que en los 500 arboles que variables han tenido más peso de manera sistemática en todos los modelos. Este valor no lo puedes interpretar pero te hace un ranking, cuanto más altos mejor (Accuracy y Gini). En vez de conocer la significatividad estadística tienemos la importancia de las variables en el modelo. El random forest va apartando poco a pode preditores que no sean relevantes para el modelo, según va haciendo los modelos de manera altearia.</p>
<p>Cuanto mayor es el número dentro del Accuracy, más relevante es esa variable dentro de la predicción. Que una variable sea más importante que otra no implica que sea mejor, ya que al no tener ninguna medida como el p-valor no se puede saber si la variable es significativa o no. Por tanto, que una variable sea más importante no la hace relevante en sí.</p>
<p>En este modelo el type se llama “prob” y luego si entre corchetes se pone [1] clasifica sobre los 0 y [,2] quiere decir que clasifica sobre los 1.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos los valores predichos en el conjunto de test</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>predicted_rf <span class="ot">&lt;-</span> <span class="fu">predict</span>(rf.vox, <span class="at">newdata =</span> test.data, <span class="at">type =</span> <span class="st">"prob"</span>)[, <span class="dv">2</span>]</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el objeto de predicción para ROC</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>pred_rf <span class="ot">&lt;-</span> <span class="fu">prediction</span>(predicted_rf, clase_real) <span class="co"># valores predichos, valores reales</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos rendimiento (ROC)</span></span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>perf_rf <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_rf, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Pintamos la curva ROC</span></span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) </span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_rf, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"gold"</span>, <span class="at">main =</span> <span class="st">"Random Forest ROC Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reg-logistica_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos el AUC</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>auc.rf<span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_rf, <span class="at">measure =</span> <span class="st">"auc"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>) </span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>auc.rf<span class="sc">@</span>y.values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.8862379</code></pre>
</div>
</div>
<p>En este caso, AUC es de 88,7%. Esto indica que en el 87% de los casos, el modelo clasifica correctamente.</p>
</section>
<section id="modelo-de-clasificación-naive-bayes" class="level3">
<h3 class="anchored" data-anchor-id="modelo-de-clasificación-naive-bayes">Modelo de clasificación Naive Bayes</h3>
<p>Repetimos el proceso con el algoritmo <a href="https://www.r-bloggers.com/2021/04/naive-bayes-classification-in-r/">Naive Bayes</a> (misma filosofía que un modelo bayesiano pero es otro modelo de clasificación).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)  </span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Entrenamos el modelo Naive Bayes </span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>nb_model <span class="ot">&lt;-</span> <span class="fu">naiveBayes</span>(</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  intvox <span class="sc">~</span> hombre <span class="sc">+</span> estudios_universitarios <span class="sc">+</span> edad <span class="sc">+</span> ecoesp <span class="sc">+</span> ideol <span class="sc">+</span> recuerdo19, <span class="at">data =</span> train.data)</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos los valores predichos en el conjunto de test</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a>predicted_nb <span class="ot">&lt;-</span> <span class="fu">predict</span>(nb_model, <span class="at">newdata =</span> test.data, <span class="at">type =</span> <span class="st">"raw"</span>)[, <span class="dv">2</span>] <span class="co"># raw en esta librería equivale a prob en la de random.forest</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Creamos el objeto de predicción para ROC</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>pred_nb <span class="ot">&lt;-</span> <span class="fu">prediction</span>(predicted_nb, clase_real) <span class="co">#comparar datos predichos con reales</span></span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos el rendimiento (ROC)</span></span>
<span id="cb43-14"><a href="#cb43-14" aria-hidden="true" tabindex="-1"></a>perf_nb <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_nb, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>)</span>
<span id="cb43-15"><a href="#cb43-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-16"><a href="#cb43-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Pintamos la curva ROC</span></span>
<span id="cb43-17"><a href="#cb43-17" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)) <span class="co"># Configuración de un solo gráfico</span></span>
<span id="cb43-18"><a href="#cb43-18" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_nb, <span class="at">lty =</span> <span class="dv">1</span>, <span class="at">col =</span> <span class="st">"steelblue"</span>, <span class="at">main =</span> <span class="st">"Naive Bayes ROC Curve"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reg-logistica_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculamos el AUC</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>auc.nb<span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_nb, <span class="at">measure =</span> <span class="st">"auc"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>) </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>auc.nb<span class="sc">@</span>y.values </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.9161327</code></pre>
</div>
</div>
<p>En este caso, el porcentaje de casos correctamente clasificados es 91,6%.</p>
<p>Para tener una visión global vamos a representar todas las curvas ROC de manera conjunta. Esto nos permite comparar los resultados de los tres algoritmos:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_logit, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">"darkgrey"</span>, <span class="at">main =</span> <span class="st">"ROC Curves"</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_rf, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">"gold"</span>, <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_nb, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">"steelblue"</span>, <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="fl">0.4</span>, <span class="fl">0.6</span>,  </span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">"Logit=0.920"</span>, <span class="st">"Random Forest=0.887"</span>, <span class="st">"Naive Bayes=0.916"</span>), </span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>),       </span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>,</span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">"darkgrey"</span>, <span class="st">"gold"</span>,<span class="st">"steelblue"</span>),</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reg-logistica_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>Es importante recordar que nuestros modelos sólo están teniendo en consideración a los individuos que han respondido a todas las preguntas incluidas en el modelo. De esta manera, estamos dejando fuera a muchos entrevistados que no ofrecen información sobre alguna de las variables, particularmente, ideología y recuerdo. Esto genera un importante sesgo. ¿Sería mejor dejar estas variables fuera? A modo de ejemplo, vamos a ver cuál hubiera sido el resultado de no haber incluido información sobre esas variables. Repitamos nuestro modelo original, esta vez excluyendo ideología y recuerdo de voto en el 2019.</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Modelo sin ideología ni recuerdo de voto</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>logit2.vox <span class="ot">&lt;-</span> <span class="fu">glm</span>(intvox <span class="sc">~</span> hombre <span class="sc">+</span> estudios_universitarios <span class="sc">+</span> edad <span class="sc">+</span> ecoesp, <span class="at">data =</span> train.data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Predicción</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>predicted_logit2<span class="ot">&lt;-</span> <span class="fu">predict</span>(logit2.vox, <span class="at">newdata=</span>test.data, <span class="at">type=</span><span class="st">"response"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>pred_logit2 <span class="ot">&lt;-</span>  <span class="fu">prediction</span>(predicted_logit2, clase_real)</span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>perf_logit2<span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_logit2, <span class="at">measure =</span> <span class="st">"tpr"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>) </span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a><span class="co"># AUC</span></span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>auc.logit2 <span class="ot">&lt;-</span> <span class="fu">performance</span>(pred_logit2, <span class="at">measure =</span> <span class="st">"auc"</span>, <span class="at">x.measure =</span> <span class="st">"fpr"</span>) </span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>auc.logit2<span class="sc">@</span>y.values</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[[1]]
[1] 0.7653978</code></pre>
</div>
</div>
<p>La AUC en este caso es considerablemente más baja. Comparamos ambos modelos gráficamente:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_logit, <span class="at">lty=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">"darkgrey"</span>, <span class="at">main =</span> <span class="st">"Logit ROC Curves"</span>)</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(perf_logit2, <span class="at">lty=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"grey"</span>, <span class="at">add =</span> <span class="cn">TRUE</span>)</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="fl">0.4</span>, <span class="fl">0.6</span>,  </span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>       <span class="fu">c</span>(<span class="st">"Logit=0.920"</span>, <span class="st">"Logit(sin ideología ni recuerdo de voto)=0.765"</span>), </span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>       <span class="at">lty =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>),       </span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>,</span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">col=</span><span class="fu">c</span>(<span class="st">"darkgrey"</span>, <span class="st">"grey"</span>),</span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.7</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="reg-logistica_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:60.0%"></p>
</figure>
</div>
</div>
</div>
<p>Como se puede observar en el gráfico arriba, la predicción es mucho peor cuando no disponemos de información sobre ideología y recuerdo de voto. Una alternativa sería imputar los valores perdidos en las variables que tienen un número elevado de NA antes de hacer la regresión.</p>
</section>
</section>
<section id="mejora-de-modelos" class="level2">
<h2 class="anchored" data-anchor-id="mejora-de-modelos">Mejora de modelos</h2>
<p>Vamos a explorar qué ocurre si tomamos en consideración que algunas variables pueden no tener un efecto lineal. Por ejemplo, la edad. Sabemos por otros estudios que el perfil de edad de los votantes de Vox es diverso, pero el partido tiene un respaldo importante entre votantes de mediana edad (35-54 años). Para tomar en cuenta esto, vamos a elevar ambos la variable edad al cuadrado. Recordad que siempre hay que incluir el efecto principal y el cuadrático</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>logit3.vox <span class="ot">&lt;-</span> <span class="fu">glm</span>(intvox <span class="sc">~</span> hombre <span class="sc">+</span> estudios_universitarios <span class="sc">+</span> edad <span class="sc">+</span> <span class="fu">I</span>(edad<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> ecoesp <span class="sc">+</span> ideol <span class="sc">+</span> recuerdo19,</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> train.data, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(logit3.vox)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = intvox ~ hombre + estudios_universitarios + edad + 
    I(edad^2) + ecoesp + ideol + recuerdo19, family = "binomial", 
    data = train.data)

Coefficients:
                                Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept)                   -3.9443595  0.4471310  -8.821  &lt; 2e-16 ***
hombreHombre                   0.5160163  0.0912237   5.657 1.54e-08 ***
estudios_universitarioscon EU -0.2110982  0.0891749  -2.367 0.017921 *  
edad                           0.0361276  0.0166679   2.167 0.030197 *  
I(edad^2)                     -0.0005431  0.0001611  -3.372 0.000747 ***
ecoesppositiva                -1.3912122  0.1335494 -10.417  &lt; 2e-16 ***
ideol                          0.2082346  0.0220012   9.465  &lt; 2e-16 ***
recuerdo19PP                   0.9575919  0.1427256   6.709 1.96e-11 ***
recuerdo19VOX                  2.6741532  0.1477779  18.096  &lt; 2e-16 ***
recuerdo19Podemos             -0.4081878  0.2457836  -1.661 0.096761 .  
recuerdo19Ciudadanos           0.5629760  0.1688350   3.334 0.000855 ***
recuerdo19Más Madrid          -1.1715752  1.0172350  -1.152 0.249434    
recuerdo19Otros               -0.6173077  0.2172718  -2.841 0.004495 ** 
recuerdo19En blanco           -0.9736638  0.5261391  -1.851 0.064230 .  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 5182.6  on 5941  degrees of freedom
Residual deviance: 3430.9  on 5928  degrees of freedom
AIC: 3458.9

Number of Fisher Scoring iterations: 6</code></pre>
</div>
</div>
<p>En nuestro modelo, el efecto principal es positivo, y el cuadrático es negativo. Además, ambos son estadísticamente significativos. La combinación de estos efectos sugiere que la relación entre la variable independiente y la dependiente tiene forma de “U” invertida: La variable dependiente aumenta hasta cierto punto (el máximo) y luego comienza a disminuir.</p>
<p>En <a href="https://stats.oarc.ucla.edu/other/mult-pkg/faq/general/faqhow-do-i-interpret-the-sign-of-the-quadratic-term-in-a-polynomial-regression/">este post</a> se explica bastante bien la relación entre signos del efecto principal y cuadrático y la forma del efecto</p>


</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="jorgeemm/Pagina_R" data-repo-id="R_kgDONhBVEg" data-category="General" data-category-id="DIC_kwDONhBVEs4Clcdh" data-mapping="pathname" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light" data-lang="es" crossorigin="anonymous" async="">
</script>
<input type="hidden" id="giscus-base-theme" value="light">
<input type="hidden" id="giscus-alt-theme" value="dark_dimmed">
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../analisis/reg-multiple.html" class="pagination-link" aria-label="Lineal múltiple">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Lineal múltiple</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
  </div>
</nav>
</div> <!-- /content -->




</body></html>